version: "3.9"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /docker/data/postgres:/var/lib/postgresql/data
    labels:
      - traefik.enable=true
      - traefik.tcp.services.postgres.loadbalancer.server.port=5432
      - traefik.tcp.routers.postgres.entrypoints=postgres
      - traefik.tcp.routers.postgres.rule=HostSNI(`*`)
      - traefik.tcp.routers.postgres.tls=false
      - traefik.tcp.routers.postgres.service=postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=default
      - PGDATA=/var/lib/postgresql/data/pgdata
networks:
  proxy:
    external: true
