version: "3.9"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 5432:5432/tcp
    volumes:
      - /docker/data/postgres:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=default
      - PGDATA=/var/lib/postgresql/data/pgdata
networks:
  proxy:
    external: true
