version: "3.9"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/config/jellyfin:/config
      - /docker/data/media:/data/media:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vod.rule=Host(`vod.${DOMAIN}`)"
      - "traefik.http.routers.vod.entrypoints=websecure"
      - "traefik.http.routers.vod.service=vod"
      - "traefik.http.routers.vod.tls=true"
      - "traefik.http.routers.vod.middlewares=streaming@file"
      - "traefik.http.services.vod.loadbalancer.server.port=8096"

networks:
  proxy:
    external: true
