version: "3.9"
services:
  rss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: rss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/config/rss:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss.rule=Host(`rss.${DOMAIN}`)"
      - "traefik.http.routers.rss.entrypoints=websecure"
      - "traefik.http.routers.rss.service=rss"
      - "traefik.http.routers.rss.tls=true"
      - "traefik.http.routers.rss.middlewares=auth@file,default@file"
      - "traefik.http.services.rss.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
